name: "ecommerce_analytics"
version: "1.0.0"
config-version: 2

profile: "default"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

vars:
    ecommerce_schema: "dbt_test"

models:
    ecommerce_analytics:
        staging:
            +materialized: view
        marts:
            +materialized: materialized_view
