name: 'nextgen_marketing_ssot'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  nextgen_marketing_ssot:
    # Phase 3: Modeling Base Tables
    staging:
      +materialized: view
    # Phase 4: Visualization Outputs
    marts:
      +materialized: materialized_view